export const FETCH_NOTES_START = 'FETCH_NOTES_START';
export const FETCH_NOTES_SUCCESS = 'FETCH_NOTES_SUCCESS';
export const FETCH_NOTES_FAILURE = 'FETCH_NOTES_FAILURE';

export const FETCH_NOTE_ID_START = 'FETCH_NOTE_ID_START';
export const FETCH_NOTE_ID_FAILURE = 'FETCH_NOTE_ID_FAILURE';
export const FETCH_NOTE_ID_SUCCESS = 'FETCH_NOTE_ID_SUCCESS';

export const SET_ACTIVE_NOTE = 'SET_ACTIVE_NOTE';
export const EDIT_NOTE = 'EDIT_NOTE';

export const DELETE_ITEM = 'DELETE_ITEM';

export const SEARCH_FILTER = 'SEARCH_FILTER';

export const CREATE_NEW_NOTE = 'CREATE_NEW_NOTE';
