export const FETCH_NOTES_START = 'FETCH_NOTES_START';
export const FETCH_NOTES_SUCCESS = 'FETCH_NOTES_SUCCESS';
export const FETCH_NOTES_FAILURE = 'FETCH_NOTES_FAILURE';

export const SET_ACTIVE_NOTE = 'SET_ACTIVE_NOTE';
export const EDIT_NOTE = 'EDIT_NOTE';
